(add-to-list 'load-path "~/.emacs.d/site-lisp/emacs-application-framework/")
(require 'ess)
(require 'eaf)
(require 'eaf-image-viewer)
(require 'eaf-mindmap)
(require 'eaf-pdf-viewer)
(require 'eaf-browser)
(require 'eaf-video-player)
(require 'eaf-system-monitor)
(require 'eaf-music-player)
(require 'eaf-markdown-previewer)
;; (require 'eaf-mermaid)
(require 'eaf-airshare)
(require 'eaf-org-previewer)
(require 'eaf-file-browser)
(require 'eaf-rss-reader)
(require 'eaf-file-sender)
(require 'eaf-file-manager)
(require 'eaf-jupyter)
(require 'eaf-terminal)
